language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g gulp

services:
  - mongodb

before_script:
  # Special config for Chrome on Travis-CI
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp ci-client
  - gulp ci-server


